services:
  andino_isaac:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: andino_isaac
    container_name: andino_isaac
    network_mode: host
    ipc: host
    working_dir: /home/isaac-sim/ws/
    runtime: nvidia
    privileged: true
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-10}
      - LOCAL_UID=${LOCAL_UID}
      - LOCAL_GID=${LOCAL_GID}
      - OMNI_KIT_ACCEPT_EULA=Y
      - ACCEPT_EULA=Y
      - PRIVACY_CONSENT=Y
      - OMNI_USER=admin
      - OMNI_PASS=amin
      - OMNI_SERVER=https://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/5.1
      - XAUTHORITY=/tmp/.docker.xauth
      - QT_X11_NO_MITSHM=1
      - DISPLAY
    volumes:
      - $HOME/.Xauthority:/isaac-sim/.Xauthority
      # Isaac related
      - ~/docker/isaac-sim-padawan/cache/main:/isaac-sim/.cache:rw
      - ~/docker/isaac-sim-padawan/cache/computecache:/isaac-sim/.nv/ComputeCache:rw
      - ~/docker/isaac-sim-padawan/config:/isaac-sim/.nvidia-omniverse/config:rw
      - ~/docker/isaac-sim-padawan/data:/isaac-sim/.local/share/ov/data:rw
      - ~/docker/isaac-sim-padawan/logs:/isaac-sim/.nvidia-omniverse/logs:rw
      - ~/docker/isaac-sim-padawan/pkg:/isaac-sim/.local/share/ov/pkg:rw
      # Workspace
      - ..:/home/isaac-sim/ws:rw
    devices:
      - /dev/dri:/dev/dri
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
