services:
  andino_isaac:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: andino_isaac
    network_mode: host
    working_dir: /home/dev/ws/
    privileged: true
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
      - OMNI_KIT_ACCEPT_EULA=Y
      - ACCEPT_EULA=Y
      - PRIVACY_CONSENT=Y
      - NVIDIA_VISIBLE_DEVICES= all
      - NVIDIA_DRIVER_CAPABILITIES= all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      # Various Isaac directories
      - ~/docker/isaac-sim/cache:/isaac-sim/kit/cache:rw
      - ~/docker/isaac-sim/cache/.cache:/root/.cache:rw
      - ~/docker/isaac-sim/cache/computecache:/root/.nv/ComputeCache:rw
      - ~/docker/isaac-sim/cache/data:/isaac-sim/kit/data:rw
      - ~/docker/isaac-sim/kit/logs:/isaac-sim/kit/logs:rw
      - ~/docker/isaac-sim/logs:/root/.nvidia-omniverse/logs:rw
      - ~/docker/isaac-sim/data:/root/.local/share/ov/data:rw
      - ~/docker/isaac-sim/documents:/root/Documents:rw
      - ~/docker/isaac-sim/config:/root/.nvidia-omniverse/config:rw
      - ~/docker/isaac-sim/shadercache:/isaac-sim/kit/exts/omni.gpu_foundation/cache/nv_shadercache:rw
      # Workspace
      - ..:/home/dev/ws/src/andino_isaac:rw
    devices:
      - /dev/dri:/dev/dri
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
